# Generated by Django 3.0.6 on 2020-05-19 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20200519_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room', to='mainapp.Room'),
        ),
    ]
