# Generated by Django 3.0.6 on 2020-05-30 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20200529_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='turn',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
